name: Regression Tests Coverage Report

on:
  pull_request:
    paths:
    - "examples/**"
    - "test/**"
    - "!examples/landmarks/**"

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: Install dependencies
        run: npm ci

      - name: Run coverage report
        run: |
          node test/util/report.js >> coverage.log || true
